#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Render one ref->target warped YUV from a saved GOP camera-like fitting result.

Input expected from gop_camera_like_torch_lowres_rho.py:
  - gop_camera_like_result.json
  - rho_maps/rho_tXXX.npy generated by save_rho_maps()
  - original input YUV sequence

Geometry convention matches the fitting script:
  R_i, t_i maps camera_i coordinates -> GOP-local world coordinates.

For each target pixel:
  ray_t = [(x-cx)/fx, (y-cy)/fy, 1]
  X_t   = ray_t / rho_t(x,y)
  X_w   = R_t X_t + t_t
  X_r   = R_r^T (X_w - t_r)
  p_ref = K X_r

Then cv2.remap(ref frame, p_ref) synthesizes the target view.
"""

from __future__ import annotations

import argparse
import json
import os
from typing import Dict, Tuple

import numpy as np

try:
    import cv2
except ImportError as exc:
    raise ImportError("opencv-python is required: pip install opencv-python") from exc


# ============================================================
# YUV I/O
# ============================================================

def yuv420_frame_size_bytes(width: int, height: int, bitdepth: int) -> int:
    if width % 2 or height % 2:
        raise ValueError("YUV420 requires even width/height.")
    samples = width * height + 2 * ((width // 2) * (height // 2))
    if bitdepth == 8:
        return samples
    if bitdepth == 10:
        return samples * 2
    raise ValueError("Only bitdepth 8 or 10 is supported.")


def read_yuv420_frame(
    path: str,
    frame_idx: int,
    width: int,
    height: int,
    bitdepth: int,
    tenbit_shift_right: int = 0,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    fs = yuv420_frame_size_bytes(width, height, bitdepth)
    y_n = width * height
    uv_n = (width // 2) * (height // 2)
    offset = frame_idx * fs

    with open(path, "rb") as f:
        f.seek(offset)
        raw = f.read(fs)

    if len(raw) != fs:
        raise EOFError(
            f"Cannot read frame {frame_idx} from {path}: expected {fs} bytes, got {len(raw)}"
        )

    if bitdepth == 8:
        arr = np.frombuffer(raw, dtype=np.uint8)
        y = arr[:y_n].reshape(height, width).copy()
        u = arr[y_n:y_n + uv_n].reshape(height // 2, width // 2).copy()
        v = arr[y_n + uv_n:y_n + 2 * uv_n].reshape(height // 2, width // 2).copy()
    else:
        arr = np.frombuffer(raw, dtype="<u2")
        if tenbit_shift_right > 0:
            arr = arr >> tenbit_shift_right
        y = arr[:y_n].reshape(height, width).copy()
        u = arr[y_n:y_n + uv_n].reshape(height // 2, width // 2).copy()
        v = arr[y_n + uv_n:y_n + 2 * uv_n].reshape(height // 2, width // 2).copy()
        y = np.clip(y, 0, 1023).astype(np.uint16)
        u = np.clip(u, 0, 1023).astype(np.uint16)
        v = np.clip(v, 0, 1023).astype(np.uint16)

    return y, u, v


def write_yuv420_frame(
    path: str,
    y: np.ndarray,
    u: np.ndarray,
    v: np.ndarray,
    bitdepth: int,
) -> None:
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    maxv = 255 if bitdepth == 8 else 1023
    y = np.clip(np.rint(y), 0, maxv)
    u = np.clip(np.rint(u), 0, maxv)
    v = np.clip(np.rint(v), 0, maxv)

    with open(path, "wb") as f:
        if bitdepth == 8:
            f.write(y.astype(np.uint8).tobytes())
            f.write(u.astype(np.uint8).tobytes())
            f.write(v.astype(np.uint8).tobytes())
        else:
            f.write(y.astype("<u2").tobytes())
            f.write(u.astype("<u2").tobytes())
            f.write(v.astype("<u2").tobytes())


def write_mask_yuv420p(path: str, mask: np.ndarray) -> None:
    h, w = mask.shape
    y = mask.astype(np.uint8) * 255
    u = np.full((h // 2, w // 2), 128, dtype=np.uint8)
    v = np.full((h // 2, w // 2), 128, dtype=np.uint8)
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "wb") as f:
        f.write(y.tobytes())
        f.write(u.tobytes())
        f.write(v.tobytes())


# ============================================================
# Result loading
# ============================================================

def resolve_path(path: str, result_json: str) -> str:
    if not path:
        return path
    if os.path.isabs(path):
        return path

    # First interpret relative to current working directory, matching original script behavior.
    if os.path.exists(path):
        return os.path.abspath(path)

    # Then interpret relative to the JSON file directory.
    base = os.path.dirname(os.path.abspath(result_json))
    cand = os.path.join(base, path)
    return os.path.abspath(cand)


def load_result_json(path: str) -> dict:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def load_poses(result: dict) -> Dict[int, Tuple[np.ndarray, np.ndarray]]:
    poses = {}
    for p in result["poses"]:
        frame_idx = int(p["frame_idx"])
        R = np.asarray(p["R"], dtype=np.float64)
        t = np.asarray(p["t"], dtype=np.float64).reshape(3)
        if R.shape != (3, 3):
            raise ValueError(f"Pose R for frame {frame_idx} has shape {R.shape}, expected 3x3")
        poses[frame_idx] = (R, t)
    return poses


def find_rho_map_path(result: dict, result_json: str, tar_idx: int, explicit_rho_map: str | None) -> str:
    if explicit_rho_map:
        return resolve_path(explicit_rho_map, result_json)

    outputs = result.get("outputs", {})
    rho_dir = outputs.get("rho_map_dir", "")
    if rho_dir:
        rho_dir = resolve_path(rho_dir, result_json)
    else:
        rho_dir = os.path.join(os.path.dirname(os.path.abspath(result_json)), "rho_maps")

    return os.path.join(rho_dir, f"rho_t{tar_idx:03d}.npy")


# ============================================================
# Geometry / rendering
# ============================================================

def make_camera_like_maps(
    rho_img: np.ndarray,
    K: np.ndarray,
    R_tar: np.ndarray,
    t_tar: np.ndarray,
    R_ref: np.ndarray,
    t_ref: np.ndarray,
    z_min: float,
    row_batch: int,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    height, width = rho_img.shape
    fx = float(K[0, 0])
    fy = float(K[1, 1])
    cx = float(K[0, 2])
    cy = float(K[1, 2])

    map_x = np.zeros((height, width), dtype=np.float32)
    map_y = np.zeros((height, width), dtype=np.float32)
    valid = np.zeros((height, width), dtype=bool)

    xs_full = np.arange(width, dtype=np.float64)
    row_batch = max(1, int(row_batch))

    for y0 in range(0, height, row_batch):
        y1 = min(height, y0 + row_batch)
        ys = np.arange(y0, y1, dtype=np.float64)
        xs, yy = np.meshgrid(xs_full, ys)

        rho = rho_img[y0:y1, :].reshape(-1).astype(np.float64)
        rho_ok = np.isfinite(rho) & (rho > 1e-12)
        rho_safe = np.where(rho_ok, rho, 1.0)

        ray_x = (xs.reshape(-1) - cx) / fx
        ray_y = (yy.reshape(-1) - cy) / fy
        rays = np.stack([ray_x, ray_y, np.ones_like(ray_x)], axis=1)

        X_tar = rays / rho_safe[:, None]
        X_w = X_tar @ R_tar.T + t_tar[None, :]
        X_ref = (X_w - t_ref[None, :]) @ R_ref

        z = X_ref[:, 2]
        z_safe = np.where(np.abs(z) > 1e-9, z, 1e-9)
        mx = fx * (X_ref[:, 0] / z_safe) + cx
        my = fy * (X_ref[:, 1] / z_safe) + cy

        ok = (
            rho_ok
            & (z > z_min)
            & np.isfinite(mx)
            & np.isfinite(my)
            & (mx >= 0.0)
            & (mx <= width - 1.0)
            & (my >= 0.0)
            & (my <= height - 1.0)
        )

        map_x[y0:y1, :] = mx.reshape(y1 - y0, width).astype(np.float32)
        map_y[y0:y1, :] = my.reshape(y1 - y0, width).astype(np.float32)
        valid[y0:y1, :] = ok.reshape(y1 - y0, width)

    map_x[~valid] = -1.0
    map_y[~valid] = -1.0
    return map_x, map_y, valid


def chroma_maps_from_luma(map_x: np.ndarray, map_y: np.ndarray, valid: np.ndarray) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    h, w = map_x.shape
    cw, ch = w // 2, h // 2
    cmx = cv2.resize(map_x, (cw, ch), interpolation=cv2.INTER_LINEAR) * 0.5
    cmy = cv2.resize(map_y, (cw, ch), interpolation=cv2.INTER_LINEAR) * 0.5
    cvalid_f = cv2.resize(valid.astype(np.float32), (cw, ch), interpolation=cv2.INTER_AREA)
    cvalid = cvalid_f > 0.999
    cmx[~cvalid] = -1.0
    cmy[~cvalid] = -1.0
    return cmx.astype(np.float32), cmy.astype(np.float32), cvalid


def remap_plane(
    plane: np.ndarray,
    map_x: np.ndarray,
    map_y: np.ndarray,
    valid: np.ndarray,
    interpolation: int,
    border_mode: int,
    border_value: float,
) -> np.ndarray:
    out = cv2.remap(
        plane.astype(np.float32),
        map_x.astype(np.float32),
        map_y.astype(np.float32),
        interpolation=interpolation,
        borderMode=border_mode,
        borderValue=float(border_value),
    )
    out[~valid] = border_value
    return out


def fill_invalid_with_target(
    warped: Tuple[np.ndarray, np.ndarray, np.ndarray],
    target: Tuple[np.ndarray, np.ndarray, np.ndarray],
    valid_y: np.ndarray,
    valid_uv: np.ndarray,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    wy, wu, wv = warped
    ty, tu, tv = target
    oy, ou, ov = wy.copy(), wu.copy(), wv.copy()
    oy[~valid_y] = ty.astype(np.float32)[~valid_y]
    ou[~valid_uv] = tu.astype(np.float32)[~valid_uv]
    ov[~valid_uv] = tv.astype(np.float32)[~valid_uv]
    return oy, ou, ov


def y_metrics(pred_y: np.ndarray, target_y: np.ndarray, valid: np.ndarray, bitdepth: int) -> Tuple[float | None, float | None, float | None]:
    if not np.any(valid):
        return None, None, None
    diff = pred_y.astype(np.float64)[valid] - target_y.astype(np.float64)[valid]
    mae = float(np.mean(np.abs(diff)))
    mse = float(np.mean(diff * diff))
    maxv = float(255 if bitdepth == 8 else 1023)
    psnr = float("inf") if mse <= 0.0 else float(10.0 * np.log10((maxv * maxv) / mse))
    return mae, mse, psnr


def save_diff_png(path: str, target_y: np.ndarray, pred_y: np.ndarray, valid: np.ndarray, bitdepth: int) -> None:
    diff = np.abs(target_y.astype(np.float32) - pred_y.astype(np.float32))
    if np.any(valid):
        scale = float(np.percentile(diff[valid], 99))
    else:
        scale = float(np.percentile(diff, 99))
    scale = max(scale, 1.0)
    diff8 = np.clip(diff / scale * 255.0, 0, 255).astype(np.uint8)
    color = cv2.applyColorMap(diff8, cv2.COLORMAP_JET)
    color[~valid] = (0, 0, 0)
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    cv2.imwrite(path, color)


# ============================================================
# CLI
# ============================================================

def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Render selected ref->target YUV from saved GOP camera-like fitting result")
    p.add_argument("--result-json", required=True, help="gop_camera_like_result.json")
    p.add_argument("--input", default="", help="Original YUV sequence. If omitted, uses result JSON input field.")
    p.add_argument("--tar-idx", type=int, required=True, help="target frame index")
    p.add_argument("--ref-idx", type=int, required=True, help="reference frame index")
    p.add_argument("--output-prefix", required=True)

    p.add_argument("--width", type=int, default=0, help="override width")
    p.add_argument("--height", type=int, default=0, help="override height")
    p.add_argument("--bitdepth", type=int, choices=[0, 8, 10], default=0, help="override bitdepth")
    p.add_argument("--rho-map", default="", help="optional explicit rho_tXXX.npy path")
    p.add_argument("--tenbit-shift-right", type=int, default=0, help="Use 6 only if 10-bit samples are MSB-aligned in uint16.")

    p.add_argument("--interp", choices=["linear", "nearest", "cubic"], default="linear")
    p.add_argument("--border", choices=["constant", "replicate"], default="constant")
    p.add_argument("--invalid-fill", choices=["black", "neutral", "copy_target"], default="black")
    p.add_argument("--z-min", type=float, default=None, help="override z_min. Default reads fit_options.z_min or 1e-4.")
    p.add_argument("--render-row-batch", type=int, default=64)
    p.add_argument("--no-mask", action="store_true")
    p.add_argument("--no-target", action="store_true")
    p.add_argument("--no-diff-png", action="store_true")
    return p.parse_args()


def main() -> None:
    args = parse_args()
    result_json = os.path.abspath(args.result_json)
    result = load_result_json(result_json)

    width = int(args.width or result["width"])
    height = int(args.height or result["height"])
    bitdepth = int(args.bitdepth or result["bitdepth"])
    input_yuv = args.input or result.get("input", "")
    if not input_yuv:
        raise ValueError("--input is required because result JSON has no input field")
    input_yuv = resolve_path(input_yuv, result_json)

    if not os.path.exists(input_yuv):
        raise FileNotFoundError(f"Input YUV not found: {input_yuv}")

    K = np.asarray(result["K"], dtype=np.float64)
    if K.shape != (3, 3):
        raise ValueError(f"K shape must be 3x3, got {K.shape}")

    poses = load_poses(result)
    if args.tar_idx not in poses:
        raise ValueError(f"tar_idx={args.tar_idx} not found in fitted poses. Available={sorted(poses)}")
    if args.ref_idx not in poses:
        raise ValueError(f"ref_idx={args.ref_idx} not found in fitted poses. Available={sorted(poses)}")

    rho_path = find_rho_map_path(result, result_json, args.tar_idx, args.rho_map or None)
    if not os.path.exists(rho_path):
        raise FileNotFoundError(
            f"rho map not found for target {args.tar_idx}: {rho_path}\n"
            f"This target frame must have been fitted as a target frame in GOP analysis."
        )
    rho_img = np.load(rho_path).astype(np.float32)
    if rho_img.shape != (height, width):
        raise ValueError(f"rho map shape {rho_img.shape} != {(height, width)}")

    R_tar, t_tar = poses[args.tar_idx]
    R_ref, t_ref = poses[args.ref_idx]

    z_min = args.z_min
    if z_min is None:
        z_min = float(result.get("fit_options", {}).get("z_min", 1e-4))

    ref = read_yuv420_frame(input_yuv, args.ref_idx, width, height, bitdepth, args.tenbit_shift_right)
    target = read_yuv420_frame(input_yuv, args.tar_idx, width, height, bitdepth, args.tenbit_shift_right)
    ref_y, ref_u, ref_v = ref
    tar_y, tar_u, tar_v = target

    map_x, map_y, valid_y = make_camera_like_maps(
        rho_img=rho_img,
        K=K,
        R_tar=R_tar,
        t_tar=t_tar,
        R_ref=R_ref,
        t_ref=t_ref,
        z_min=float(z_min),
        row_batch=int(args.render_row_batch),
    )

    if args.interp == "nearest":
        interp = cv2.INTER_NEAREST
    elif args.interp == "cubic":
        interp = cv2.INTER_CUBIC
    else:
        interp = cv2.INTER_LINEAR
    border_mode = cv2.BORDER_REPLICATE if args.border == "replicate" else cv2.BORDER_CONSTANT

    neutral = 128 if bitdepth == 8 else 512
    y_fill = 0.0 if args.invalid_fill in ["black", "copy_target"] else float(neutral)
    uv_fill = float(neutral)

    wy = remap_plane(ref_y, map_x, map_y, valid_y, interp, border_mode, y_fill)
    cmx, cmy, valid_uv = chroma_maps_from_luma(map_x, map_y, valid_y)
    wu = remap_plane(ref_u, cmx, cmy, valid_uv, interp, border_mode, uv_fill)
    wv = remap_plane(ref_v, cmx, cmy, valid_uv, interp, border_mode, uv_fill)

    raw_wy = wy.copy()
    if args.invalid_fill == "copy_target":
        wy, wu, wv = fill_invalid_with_target((wy, wu, wv), target, valid_y, valid_uv)

    out_warp = args.output_prefix + "_warped.yuv"
    out_target = args.output_prefix + "_target.yuv"
    out_mask = args.output_prefix + "_valid_mask_yuv420p.yuv"
    out_diff = args.output_prefix + "_diff.png"
    out_stats = args.output_prefix + "_stats.json"

    write_yuv420_frame(out_warp, wy, wu, wv, bitdepth)
    if not args.no_target:
        write_yuv420_frame(out_target, tar_y, tar_u, tar_v, bitdepth)
    if not args.no_mask:
        write_mask_yuv420p(out_mask, valid_y)
    if not args.no_diff_png:
        save_diff_png(out_diff, tar_y, raw_wy, valid_y, bitdepth)

    raw_mae, raw_mse, raw_psnr = y_metrics(raw_wy, tar_y, valid_y, bitdepth)
    final_valid = np.ones_like(valid_y, dtype=bool) if args.invalid_fill == "copy_target" else valid_y
    final_mae, final_mse, final_psnr = y_metrics(wy, tar_y, final_valid, bitdepth)

    stats = {
        "result_json": result_json,
        "input_yuv": os.path.abspath(input_yuv),
        "rho_map": os.path.abspath(rho_path),
        "tar_idx": int(args.tar_idx),
        "ref_idx": int(args.ref_idx),
        "width": int(width),
        "height": int(height),
        "bitdepth": int(bitdepth),
        "z_min": float(z_min),
        "rho_min": float(np.nanmin(rho_img)),
        "rho_max": float(np.nanmax(rho_img)),
        "rho_mean": float(np.nanmean(rho_img)),
        "valid_pixels": int(np.count_nonzero(valid_y)),
        "valid_ratio": float(np.mean(valid_y)),
        "raw_y_mae_valid": raw_mae,
        "raw_y_mse_valid": raw_mse,
        "raw_y_psnr_valid": raw_psnr,
        "final_y_mae": final_mae,
        "final_y_mse": final_mse,
        "final_y_psnr": final_psnr,
        "invalid_fill": args.invalid_fill,
        "output_warped_yuv": os.path.abspath(out_warp),
        "output_target_yuv": os.path.abspath(out_target) if not args.no_target else None,
        "output_valid_mask_yuv420p": os.path.abspath(out_mask) if not args.no_mask else None,
        "output_diff_png": os.path.abspath(out_diff) if not args.no_diff_png else None,
        "note": "Render-only ref->target warp from saved GOP camera-like fit. Uses target rho map and fixed fitted poses."
    }

    os.makedirs(os.path.dirname(out_stats) or ".", exist_ok=True)
    with open(out_stats, "w", encoding="utf-8") as f:
        json.dump(stats, f, indent=2, ensure_ascii=False)

    print("Done")
    print(f"  warped yuv : {out_warp}")
    if not args.no_target:
        print(f"  target yuv : {out_target}")
    if not args.no_mask:
        print(f"  valid mask : {out_mask}")
    if not args.no_diff_png:
        print(f"  diff png   : {out_diff}")
    print(f"  stats      : {out_stats}")
    print(f"  valid ratio: {stats['valid_ratio']:.6f}")
    if raw_mae is not None:
        print(f"  raw Y MAE(valid): {raw_mae:.6f}")
    if raw_psnr is not None:
        print(f"  raw Y PSNR(valid): {raw_psnr:.6f} dB")


if __name__ == "__main__":
    main()
