#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Bidirectional hierarchical-RA camera-motion simulation.

For each non-anchor picture:
1) Find the temporally nearest reference-eligible lower-TID picture in the past.
2) Find the temporally nearest reference-eligible lower-TID picture in the future.
3) Project the current picture's four corners and center into each reference.
4) Compute avgMvPx for each direction.
5) Convert it to the codec-style normalized motion value:

       motion4096 = avgMvPx / ((width + height) / 2.0) * 4096.0

6) Combine the two directional values with --ref-combine:
       min  : use the smaller valid directional motion (default)
       mean : average the valid directional motions
       max  : use the larger valid directional motion

7) Tool is OFF when final_motion4096 < --offset-threshold.
8) A tool-off picture is excluded from later camera-projection references.

Inputs are the merged camera JSONL and depth YUV420p10le generated by the
geometry merge script.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple

import cv2
import numpy as np


# ============================================================
# Data classes
# ============================================================

@dataclass
class CameraFrame:
    gop_idx: int
    gop_name: str
    local_poc: int
    poc: int
    depth_frame_idx: int
    rvec: np.ndarray
    tvec: np.ndarray
    K: np.ndarray
    z_sign: float
    depth_scale_real: float


@dataclass
class RefEval:
    ref: CameraFrame
    valid_points: int
    avg_mv_px: Optional[float]
    motion4096: Optional[float]
    points: List[dict]


@dataclass
class Decision:
    frame: CameraFrame
    tid: int
    coding_order: int
    is_anchor: bool
    past: Optional[RefEval]
    future: Optional[RefEval]
    final_motion4096: Optional[float]
    tool_enabled: bool
    reference_eligible: bool
    reason: str


# ============================================================
# Camera JSONL
# ============================================================

def read_camera_jsonl(path: Path) -> Tuple[dict, List[CameraFrame]]:
    header = None
    frames: List[CameraFrame] = []

    with path.open("r", encoding="utf-8") as f:
        for line_no, line in enumerate(f, 1):
            line = line.strip()
            if not line:
                continue

            obj = json.loads(line)

            if obj.get("type") == "header":
                if header is not None:
                    raise ValueError(f"{path}: duplicate header")
                header = obj
                continue

            if obj.get("type") != "frame":
                continue

            intr = obj["intrinsic"]
            K = np.array(
                [
                    [float(intr["fx"]), 0.0, float(intr["cx"])],
                    [0.0, float(intr["fy"]), float(intr["cy"])],
                    [0.0, 0.0, 1.0],
                ],
                dtype=np.float64,
            )

            frames.append(
                CameraFrame(
                    gop_idx=int(obj["gop_idx"]),
                    gop_name=str(obj.get("gop_name", f"gop{obj['gop_idx']}")),
                    local_poc=int(obj["local_poc"]),
                    poc=int(obj["poc"]),
                    depth_frame_idx=int(obj["depth_frame_idx"]),
                    rvec=np.asarray(obj["rvec"], np.float64).reshape(3),
                    tvec=np.asarray(obj["tvec"], np.float64).reshape(3),
                    K=K,
                    z_sign=float(intr.get("z_sign", 1.0)),
                    depth_scale_real=float(obj["depth_scale_real"]),
                )
            )

    if header is None:
        raise ValueError(f"{path}: header not found")
    if not frames:
        raise ValueError(f"{path}: no frame records")

    return header, frames


def rt_to_T(rvec: np.ndarray, tvec: np.ndarray) -> np.ndarray:
    T = np.eye(4, dtype=np.float64)
    T[:3, :3] = cv2.Rodrigues(rvec.reshape(3, 1))[0]
    T[:3, 3] = tvec
    return T


def reconstruct_gop_poses(
    frames: Sequence[CameraFrame],
    pose_mode: str,
) -> Dict[int, np.ndarray]:
    """
    Return A[i] = camera_i_from_camera_gop0.
    """
    ordered = sorted(frames, key=lambda x: x.local_poc)
    raw = {f.local_poc: rt_to_T(f.rvec, f.tvec) for f in ordered}
    out: Dict[int, np.ndarray] = {}

    if pose_mode == "current_to_previous":
        first = ordered[0].local_poc
        out[first] = np.eye(4, dtype=np.float64)

        for prev, cur in zip(ordered[:-1], ordered[1:]):
            if cur.local_poc != prev.local_poc + 1:
                raise ValueError(
                    f"GOP {cur.gop_idx}: non-contiguous local POC "
                    f"{prev.local_poc}->{cur.local_poc}"
                )

            # raw[cur] = camera_(cur-1)_from_camera_cur
            out[cur.local_poc] = (
                np.linalg.inv(raw[cur.local_poc]) @ out[prev.local_poc]
            )

    elif pose_mode == "gop_local":
        for f in ordered:
            out[f.local_poc] = raw[f.local_poc]

    elif pose_mode == "absolute":
        inv_T0 = np.linalg.inv(raw[ordered[0].local_poc])
        for f in ordered:
            out[f.local_poc] = raw[f.local_poc] @ inv_T0

    else:
        raise ValueError(f"unsupported pose mode: {pose_mode}")

    return out


# ============================================================
# Depth YUV reader
# ============================================================

class DepthYUV420P10LE:
    def __init__(self, path: Path, width: int, height: int):
        if width <= 0 or height <= 0 or width % 2 or height % 2:
            raise ValueError("YUV420 requires positive even width/height")

        self.path = path
        self.width = width
        self.height = height
        self.y_samples = width * height
        self.uv_samples = (width // 2) * (height // 2)
        self.frame_bytes = (
            self.y_samples + 2 * self.uv_samples
        ) * 2

        size = path.stat().st_size
        if size % self.frame_bytes:
            raise ValueError(
                f"{path}: invalid file size {size} for frame size "
                f"{self.frame_bytes}"
            )

        self.frame_count = size // self.frame_bytes
        self.fp = path.open("rb")

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc, tb):
        self.fp.close()

    def read_y(self, frame_idx: int) -> np.ndarray:
        if not (0 <= frame_idx < self.frame_count):
            raise IndexError(
                f"depth frame {frame_idx} outside [0,{self.frame_count})"
            )

        self.fp.seek(frame_idx * self.frame_bytes)
        raw = self.fp.read(self.y_samples * 2)
        if len(raw) != self.y_samples * 2:
            raise EOFError(f"short Y read at frame {frame_idx}")

        return np.frombuffer(raw, dtype="<u2").reshape(
            self.height, self.width
        )


# ============================================================
# Hierarchical RA
# ============================================================

def assign_hierarchical_tid(local_pocs: Sequence[int]) -> Dict[int, int]:
    pocs = sorted(set(int(x) for x in local_pocs))

    if len(pocs) == 1:
        return {pocs[0]: 0}

    tid = {pocs[0]: 0, pocs[-1]: 0}

    def recurse(lo: int, hi: int, level: int) -> None:
        if hi - lo <= 1:
            return

        mid = (lo + hi) // 2
        tid[pocs[mid]] = level

        recurse(lo, mid, level + 1)
        recurse(mid, hi, level + 1)

    recurse(0, len(pocs) - 1, 1)

    fallback_tid = max(tid.values(), default=0) + 1
    for p in pocs:
        tid.setdefault(p, fallback_tid)

    return tid


def ra_coding_order(
    frames: Sequence[CameraFrame],
    tids: Dict[int, int],
) -> List[CameraFrame]:
    return sorted(
        frames,
        key=lambda f: (tids[f.local_poc], f.local_poc),
    )


def nearest_directional_reference(
    current: CameraFrame,
    current_tid: int,
    decisions: Sequence[Decision],
    direction: str,
) -> Optional[CameraFrame]:
    candidates = []

    for d in decisions:
        if not d.reference_eligible:
            continue
        if d.tid >= current_tid:
            continue

        delta = d.frame.local_poc - current.local_poc

        if direction == "past" and delta < 0:
            candidates.append(d.frame)
        elif direction == "future" and delta > 0:
            candidates.append(d.frame)

    if not candidates:
        return None

    return min(
        candidates,
        key=lambda f: (
            abs(f.local_poc - current.local_poc),
            f.local_poc,
        ),
    )


# ============================================================
# Projection
# ============================================================

def sample_points(
    width: int,
    height: int,
    inset: int,
) -> List[Tuple[str, int, int]]:
    x0 = min(max(0, inset), width - 1)
    y0 = min(max(0, inset), height - 1)
    x1 = max(0, width - 1 - inset)
    y1 = max(0, height - 1 - inset)

    return [
        ("top_left", x0, y0),
        ("top_right", x1, y0),
        ("bottom_left", x0, y1),
        ("bottom_right", x1, y1),
        ("center", (width - 1) // 2, (height - 1) // 2),
    ]


def project_target_to_reference(
    x: float,
    y: float,
    depth: float,
    target: CameraFrame,
    reference: CameraFrame,
    poses: Dict[int, np.ndarray],
) -> Optional[Tuple[float, float]]:
    if not np.isfinite(depth) or depth <= 0:
        return None

    ray = np.linalg.inv(target.K) @ np.array(
        [x, y, 1.0],
        dtype=np.float64,
    )
    X_target = ray * (depth * target.z_sign)

    T_ref_from_target = (
        poses[reference.local_poc]
        @ np.linalg.inv(poses[target.local_poc])
    )

    X_ref = (
        T_ref_from_target[:3, :3] @ X_target
        + T_ref_from_target[:3, 3]
    )

    z = float(X_ref[2])
    if not np.isfinite(z) or abs(z) < 1e-12:
        return None
    if z * target.z_sign <= 0:
        return None

    q = reference.K @ X_ref
    u = float(q[0] / q[2])
    v = float(q[1] / q[2])

    if not (np.isfinite(u) and np.isfinite(v)):
        return None

    return u, v


def evaluate_reference(
    target: CameraFrame,
    reference: CameraFrame,
    depth_code: np.ndarray,
    poses: Dict[int, np.ndarray],
    width: int,
    height: int,
    inset: int,
) -> RefEval:
    motions: List[float] = []
    points: List[dict] = []

    for name, x, y in sample_points(width, height, inset):
        code = int(depth_code[y, x])
        depth = code * target.depth_scale_real

        projected = project_target_to_reference(
            float(x),
            float(y),
            float(depth),
            target,
            reference,
            poses,
        )

        if projected is None:
            points.append(
                {
                    "name": name,
                    "valid": False,
                    "x": x,
                    "y": y,
                    "depth": float(depth),
                    "ref_x": None,
                    "ref_y": None,
                    "mv_px": None,
                }
            )
            continue

        u, v = projected
        mv_px = math.hypot(u - x, v - y)
        motions.append(mv_px)

        points.append(
            {
                "name": name,
                "valid": True,
                "x": x,
                "y": y,
                "depth": float(depth),
                "ref_x": u,
                "ref_y": v,
                "mv_px": mv_px,
            }
        )

    if motions:
        avg_mv_px = float(np.mean(np.asarray(motions, np.float64)))
        motion4096 = (
            avg_mv_px
            / ((width + height) / 2.0)
            * 4096.0
        )
    else:
        avg_mv_px = None
        motion4096 = None

    return RefEval(
        ref=reference,
        valid_points=len(motions),
        avg_mv_px=avg_mv_px,
        motion4096=motion4096,
        points=points,
    )


def combine_directional_motion(
    past: Optional[RefEval],
    future: Optional[RefEval],
    min_valid_points: int,
    mode: str,
) -> Tuple[Optional[float], str]:
    valid_values = []

    if (
        past is not None
        and past.valid_points >= min_valid_points
        and past.motion4096 is not None
    ):
        valid_values.append(past.motion4096)

    if (
        future is not None
        and future.valid_points >= min_valid_points
        and future.motion4096 is not None
    ):
        valid_values.append(future.motion4096)

    if not valid_values:
        return None, "no_valid_direction"

    if mode == "min":
        return min(valid_values), "min_directional_motion"
    if mode == "mean":
        return float(np.mean(valid_values)), "mean_directional_motion"
    if mode == "max":
        return max(valid_values), "max_directional_motion"

    raise ValueError(mode)


# ============================================================
# Simulation
# ============================================================

def simulate_gop(
    frames: Sequence[CameraFrame],
    pose_mode: str,
    depth_reader: DepthYUV420P10LE,
    width: int,
    height: int,
    threshold: float,
    ref_combine: str,
    min_valid_points: int,
    corner_inset: int,
    allow_anchor_off: bool,
) -> List[Decision]:
    by_local = {f.local_poc: f for f in frames}
    if len(by_local) != len(frames):
        raise ValueError(
            f"GOP {frames[0].gop_idx}: duplicate local_poc"
        )

    tids = assign_hierarchical_tid(list(by_local))
    order = ra_coding_order(frames, tids)
    poses = reconstruct_gop_poses(frames, pose_mode)

    anchors = {min(by_local), max(by_local)}
    decisions: List[Decision] = []

    for coding_order, frame in enumerate(order):
        tid = tids[frame.local_poc]
        is_anchor = frame.local_poc in anchors

        if is_anchor and not allow_anchor_off:
            decisions.append(
                Decision(
                    frame=frame,
                    tid=tid,
                    coding_order=coding_order,
                    is_anchor=True,
                    past=None,
                    future=None,
                    final_motion4096=None,
                    tool_enabled=True,
                    reference_eligible=True,
                    reason="anchor_forced_on",
                )
            )
            continue

        depth = depth_reader.read_y(frame.depth_frame_idx)

        past_ref = nearest_directional_reference(
            frame,
            tid,
            decisions,
            "past",
        )
        future_ref = nearest_directional_reference(
            frame,
            tid,
            decisions,
            "future",
        )

        past_eval = (
            evaluate_reference(
                frame,
                past_ref,
                depth,
                poses,
                width,
                height,
                corner_inset,
            )
            if past_ref is not None
            else None
        )

        future_eval = (
            evaluate_reference(
                frame,
                future_ref,
                depth,
                poses,
                width,
                height,
                corner_inset,
            )
            if future_ref is not None
            else None
        )

        final_motion4096, combine_reason = combine_directional_motion(
            past_eval,
            future_eval,
            min_valid_points,
            ref_combine,
        )

        if final_motion4096 is None:
            tool_enabled = True
            reference_eligible = True
            reason = "insufficient_valid_points_keep_on"
        elif final_motion4096 < threshold:
            tool_enabled = False
            reference_eligible = False
            reason = (
                f"{combine_reason}_below_threshold"
            )
        else:
            tool_enabled = True
            reference_eligible = True
            reason = (
                f"{combine_reason}_at_or_above_threshold"
            )

        decisions.append(
            Decision(
                frame=frame,
                tid=tid,
                coding_order=coding_order,
                is_anchor=is_anchor,
                past=past_eval,
                future=future_eval,
                final_motion4096=final_motion4096,
                tool_enabled=tool_enabled,
                reference_eligible=reference_eligible,
                reason=reason,
            )
        )

    return sorted(decisions, key=lambda d: d.frame.local_poc)


# ============================================================
# Output
# ============================================================

def ref_columns(prefix: str, ev: Optional[RefEval]) -> dict:
    return {
        f"{prefix}_ref_local_poc": (
            None if ev is None else ev.ref.local_poc
        ),
        f"{prefix}_ref_poc": (
            None if ev is None else ev.ref.poc
        ),
        f"{prefix}_temporal_distance": (
            None
            if ev is None
            else abs(ev.ref.local_poc)
        ),
        f"{prefix}_valid_points": (
            0 if ev is None else ev.valid_points
        ),
        f"{prefix}_avg_mv_px": (
            None if ev is None else ev.avg_mv_px
        ),
        f"{prefix}_motion4096": (
            None if ev is None else ev.motion4096
        ),
    }


def write_csv(path: Path, decisions: Sequence[Decision]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)

    fields = [
        "gop_idx",
        "gop_name",
        "local_poc",
        "poc",
        "depth_frame_idx",
        "tid",
        "coding_order",
        "is_anchor",
        "past_ref_local_poc",
        "past_ref_poc",
        "past_temporal_distance",
        "past_valid_points",
        "past_avg_mv_px",
        "past_motion4096",
        "future_ref_local_poc",
        "future_ref_poc",
        "future_temporal_distance",
        "future_valid_points",
        "future_avg_mv_px",
        "future_motion4096",
        "final_motion4096",
        "tool_enabled",
        "reference_eligible",
        "reason",
    ]

    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fields)
        writer.writeheader()

        for d in decisions:
            row = {
                "gop_idx": d.frame.gop_idx,
                "gop_name": d.frame.gop_name,
                "local_poc": d.frame.local_poc,
                "poc": d.frame.poc,
                "depth_frame_idx": d.frame.depth_frame_idx,
                "tid": d.tid,
                "coding_order": d.coding_order,
                "is_anchor": int(d.is_anchor),
                "final_motion4096": d.final_motion4096,
                "tool_enabled": int(d.tool_enabled),
                "reference_eligible": int(d.reference_eligible),
                "reason": d.reason,
            }

            row.update(ref_columns("past", d.past))
            row.update(ref_columns("future", d.future))

            # Correct temporal distances relative to the current picture.
            if d.past is not None:
                row["past_temporal_distance"] = abs(
                    d.frame.local_poc - d.past.ref.local_poc
                )
            if d.future is not None:
                row["future_temporal_distance"] = abs(
                    d.frame.local_poc - d.future.ref.local_poc
                )

            writer.writerow(row)


def write_mask_jsonl(
    path: Path,
    header: dict,
    decisions: Sequence[Decision],
    args,
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)

    with path.open("w", encoding="utf-8") as f:
        f.write(
            json.dumps(
                {
                    "type": "header",
                    "format": "camproj_ra_bidir_mask_v1",
                    "sequence_name": header.get("sequence_name"),
                    "width": int(header["width"]),
                    "height": int(header["height"]),
                    "pose_mode": header["pose_mode"],
                    "motion_formula": (
                        "avgMvPx / ((W + H) / 2.0) * 4096"
                    ),
                    "ref_combine": args.ref_combine,
                    "offset_threshold": args.offset_threshold,
                    "min_valid_points": args.min_valid_points,
                },
                ensure_ascii=False,
            )
            + "\n"
        )

        for d in decisions:
            f.write(
                json.dumps(
                    {
                        "type": "frame",
                        "gop_idx": d.frame.gop_idx,
                        "gop_name": d.frame.gop_name,
                        "local_poc": d.frame.local_poc,
                        "poc": d.frame.poc,
                        "tid": d.tid,
                        "past_ref_poc": (
                            None if d.past is None else d.past.ref.poc
                        ),
                        "past_motion4096": (
                            None if d.past is None else d.past.motion4096
                        ),
                        "future_ref_poc": (
                            None if d.future is None else d.future.ref.poc
                        ),
                        "future_motion4096": (
                            None if d.future is None else d.future.motion4096
                        ),
                        "final_motion4096": d.final_motion4096,
                        "tool_enabled": d.tool_enabled,
                        "reference_eligible": d.reference_eligible,
                        "reason": d.reason,
                    },
                    ensure_ascii=False,
                )
                + "\n"
            )


def build_summary(
    header: dict,
    decisions: Sequence[Decision],
    args,
) -> dict:
    by_gop: Dict[int, List[Decision]] = {}
    for d in decisions:
        by_gop.setdefault(d.frame.gop_idx, []).append(d)

    gops = {}
    for gop_idx, ds in sorted(by_gop.items()):
        off = [d for d in ds if not d.tool_enabled]
        non_anchor = [d for d in ds if not d.is_anchor]
        measured = [
            d.final_motion4096
            for d in ds
            if d.final_motion4096 is not None
        ]

        gops[str(gop_idx)] = {
            "gop_name": ds[0].frame.gop_name,
            "picture_count": len(ds),
            "tool_off_count": len(off),
            "tool_off_ratio_all": len(off) / len(ds),
            "tool_off_ratio_non_anchor": (
                len(off) / len(non_anchor)
                if non_anchor
                else 0.0
            ),
            "mean_final_motion4096": (
                float(np.mean(measured))
                if measured
                else None
            ),
            "max_final_motion4096": (
                float(np.max(measured))
                if measured
                else None
            ),
        }

    off_all = [d for d in decisions if not d.tool_enabled]
    non_anchor_all = [d for d in decisions if not d.is_anchor]

    return {
        "format": "camproj_ra_bidir_summary_v1",
        "sequence_name": header.get("sequence_name"),
        "width": int(header["width"]),
        "height": int(header["height"]),
        "pose_mode": header["pose_mode"],
        "motion_formula": "avgMvPx / ((W + H) / 2.0) * 4096",
        "ref_combine": args.ref_combine,
        "offset_threshold": args.offset_threshold,
        "min_valid_points": args.min_valid_points,
        "corner_inset": args.corner_inset,
        "total_picture_count": len(decisions),
        "total_tool_off_count": len(off_all),
        "tool_off_ratio_all": (
            len(off_all) / len(decisions)
            if decisions
            else 0.0
        ),
        "tool_off_ratio_non_anchor": (
            len(off_all) / len(non_anchor_all)
            if non_anchor_all
            else 0.0
        ),
        "gops": gops,
    }


# ============================================================
# Main
# ============================================================

def main() -> None:
    ap = argparse.ArgumentParser()

    ap.add_argument("--camera-jsonl", required=True)
    ap.add_argument(
        "--depth-yuv",
        default=None,
        help=(
            "Merged depth YUV420p10le. If omitted, use the depth_yuv "
            "field in the JSONL header."
        ),
    )
    ap.add_argument(
        "--output-prefix",
        default=None,
    )
    ap.add_argument(
        "--offset-threshold",
        required=True,
        type=float,
        help=(
            "Tool OFF threshold for "
            "avgMvPx / ((W + H) / 2.0) * 4096."
        ),
    )
    ap.add_argument(
        "--ref-combine",
        choices=["min", "mean", "max"],
        default="min",
        help=(
            "Combine past/future motion4096 values. "
            "Default=min."
        ),
    )
    ap.add_argument(
        "--min-valid-points",
        type=int,
        default=3,
    )
    ap.add_argument(
        "--corner-inset",
        type=int,
        default=0,
    )
    ap.add_argument(
        "--allow-anchor-off",
        action="store_true",
    )

    args = ap.parse_args()

    if args.offset_threshold < 0:
        raise ValueError("--offset-threshold must be nonnegative")
    if not (1 <= args.min_valid_points <= 5):
        raise ValueError("--min-valid-points must be in [1,5]")
    if args.corner_inset < 0:
        raise ValueError("--corner-inset must be nonnegative")

    camera_path = Path(args.camera_jsonl)
    header, frames = read_camera_jsonl(camera_path)

    width = int(header["width"])
    height = int(header["height"])
    pose_mode = str(header["pose_mode"])

    if args.depth_yuv:
        depth_path = Path(args.depth_yuv)
    else:
        depth_name = header.get("depth_yuv")
        if not depth_name:
            raise ValueError(
                "--depth-yuv omitted and JSONL header has no depth_yuv"
            )
        depth_path = camera_path.parent / depth_name

    if args.output_prefix:
        prefix = Path(args.output_prefix)
    else:
        prefix = camera_path.with_name(
            camera_path.stem + "_ra_bidir_sim"
        )

    grouped: Dict[int, List[CameraFrame]] = {}
    for frame in frames:
        grouped.setdefault(frame.gop_idx, []).append(frame)

    all_decisions: List[Decision] = []

    with DepthYUV420P10LE(depth_path, width, height) as depth_reader:
        for gop_idx, gop_frames in sorted(grouped.items()):
            decisions = simulate_gop(
                frames=sorted(
                    gop_frames,
                    key=lambda f: f.local_poc,
                ),
                pose_mode=pose_mode,
                depth_reader=depth_reader,
                width=width,
                height=height,
                threshold=args.offset_threshold,
                ref_combine=args.ref_combine,
                min_valid_points=args.min_valid_points,
                corner_inset=args.corner_inset,
                allow_anchor_off=args.allow_anchor_off,
            )

            all_decisions.extend(decisions)

            off_count = sum(
                not d.tool_enabled for d in decisions
            )
            print(
                f"[GOP {gop_idx}] pictures={len(decisions)}, "
                f"tool_off={off_count}, "
                f"ratio={off_count / len(decisions):.4f}"
            )

    csv_path = Path(str(prefix) + "_frames.csv")
    mask_path = Path(str(prefix) + "_mask.jsonl")
    summary_path = Path(str(prefix) + "_summary.json")

    write_csv(csv_path, all_decisions)
    write_mask_jsonl(
        mask_path,
        header,
        all_decisions,
        args,
    )

    summary = build_summary(
        header,
        all_decisions,
        args,
    )
    summary_path.parent.mkdir(parents=True, exist_ok=True)
    summary_path.write_text(
        json.dumps(summary, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )

    print(f"[OK] CSV     : {csv_path}")
    print(f"[OK] mask    : {mask_path}")
    print(f"[OK] summary : {summary_path}")
    print(
        f"[TOTAL] tool_off="
        f"{summary['total_tool_off_count']}/"
        f"{summary['total_picture_count']} "
        f"({summary['tool_off_ratio_all']:.4%})"
    )


if __name__ == "__main__":
    main()
